spring:
  data:
    mongodb:
      host: localhost # Replace with your MongoDB host (e.g., an IP address or domain)
      port: 27017     # Default MongoDB port
      database: Food_Delivery_App # Replace with your database name
      username: root     # If authentication is enabled, provide the username
      password: root      # Provide the password here if applicable
      authentication-database: admin
  application:
    name: PAYMENT-SERVICE

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG # Enable detailed logging for MongoDB interactions
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka Server
    fetch-registry: true                          # Fetch the registry from the Eureka server
    register-with-eureka: true                    # Register this application with Eureka server
  instance:
    instance-id: ${spring.application.name}:${server.port} # Unique instance ID
    prefer-ip-address: true                        # Use IP address instead of hostname

  # Logging configuration (optional)
  level:
    com.netflix.eureka: DEBUG